---
kind: pipeline
name: python-3-6

steps:
- name: test
  image: python:3.6
  commands:
  - pip install -r requirements.txt
  - pip install -e .
# matplotlib is only needed in some testing scripts (no real requirement)
  - pip install matplotlib
  - pwd
  - ls
  - ls symbtools
  - ls symbtools/test
  - python symbtools/test/run_all_tests.py all
  - pip install control casadi
  - python symbtools/test/run_all_tests.py optdep
---
kind: pipeline
name: python-3-8

steps:
- name: test
  image: python:3.8
  commands:
  - pip install -r requirements.txt
  - pip install -e .
# matplotlib is only needed in some testing scripts (no real requirement)
  - pip install matplotlib
  - pwd
  - ls
  - ls symbtools
  - ls symbtools/test
  - python symbtools/test/run_all_tests.py all
  - pip install control casadi
  - python symbtools/test/run_all_tests.py optdep

