---
kind: pipeline
name: python-3-6
type: docker

steps:
- name: test
  image: python:3.6
  commands:
  - pip install -r requirements.txt
  - pip install -e .
# matplotlib is only needed in some testing scripts (no real requirement)
  - pip install matplotlib
  - pwd
  - ls
  - ls symbtools
  - ls symbtools/test
  - python symbtools/test/run_all_tests.py all
  - pip install control casadi
  - python symbtools/test/run_all_tests.py optdep

# To save energy and resources ci should only run for a few branches
# Related section of the docs: https://docs.drone.io/pipeline/triggers/
trigger:
  branch:
    - main
    - develop

---
kind: pipeline
name: python-3-8
type: docker

steps:
- name: test
  image: python:3.8
  commands:
  - pip install -r requirements.txt
  - pip install -e .
# matplotlib is only needed in some testing scripts (no real requirement)
  - pip install matplotlib
  - pwd
  - ls
  - ls symbtools
  - ls symbtools/test
# test for a specific bug
  - python symbtools/test/test_modeltools.py ModelToolsTest.test_four_bar_constraints
  - python symbtools/test/run_all_tests.py all
  - pip install control casadi
  - python symbtools/test/run_all_tests.py optdep

# To save energy and resources ci should only run for a few branches
# Related section of the docs: https://docs.drone.io/pipeline/triggers/
trigger:
  branch:
    - main
    - develop
---
kind: pipeline
name: python-3-10
type: docker

steps:
- name: test
  image: python:3.10
  commands:
  - pip install -r requirements.txt
  - pip install -e .
# matplotlib is only needed in some testing scripts (no real requirement)
  - pip install matplotlib
  - pwd
  - ls
  - ls symbtools
  - ls symbtools/test
# test for a specific bug
  - python symbtools/test/test_modeltools.py ModelToolsTest.test_four_bar_constraints
  - python symbtools/test/run_all_tests.py all
  # currently (2021-12-21) casadi seems not to be available for python3.10
  # - pip install control casadi
  # - python symbtools/test/run_all_tests.py optdep

# To save energy and resources ci should only run for a few branches
# Related section of the docs: https://docs.drone.io/pipeline/triggers/
trigger:
  branch:
    - main
    - develop
