kind: pipeline
name: default

steps:
- name: test
  image: python
  commands:
  - pip install -r requirements.txt
  - pip install -e .
# matplotlib is only needed in some testing scripts (no real requirement)
  - pip install matplotlib
  - pwd
  - ls
  - ls symbtools
  - ls symbtools/test
  - python symbtools/test/run_all_tests.py all
