language: python

python:
  - "3.5"
  - "3.6"
  - "3.7"

install:
 - pip install -r requirements.txt
 - pip install -e .

# command to run tests
script:
# matplotlib is only needed in some testing scripts (no real requirement)
 - pip install matplotlib
 - pwd
 - ls
 - ls symbtools
 - ls symbtools/test
 - python symbtools/test/run_all_tests.py all
#  install optional dependency
 - pip install control casadi
 - python symbtools/test/run_all_tests.py optdep
